### PR TITLE
linttest now uses global eslint settings (.eslintrc.json),

### PR DESCRIPTION
**Pull request by fhnaseer**

### CODE REVIEW

**Review by PCXDME — CHANGES_REQUESTED** [review]
Actually it does already use eslint setting from ".eslintrc.json".
You can try deleting ".eslintrc.json", and it will give some errors when run "npm run test".
"options" provided to lint funtion is options of mocha-eslint.
You can see how it works here https://github.com/BadgeLabs/mocha-eslint/blob/master/index.js

**Comment by fhnaseer** [comment]
I get these errors when i run 'npm run lint',
E:\Code\Tum\javascript\JS18_ProjectB_Group4\api\controllers\functionController.js
   1:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
   2:42  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
....

But i dont get these when i run 'npm run test',

**Comment by PCXDME** [comment]
When I try changing functionController.js into CRLF linebreak style, I got errors in both "npm run lint" and "npm run test".
Here are some output of "npm run test"
image

**Comment by fhnaseer** [comment]
That's strange. I delete repo and cloned it again. Now I am getting errors on both,

**Pull request closed without merging**
