### PR TITLE
14 frontend app

### PR DESCRIPTION
**Pull request by fhnaseer**
#14 
Added a sample webpage where we can see different type of (hardcoded) charts,

### CODE REVIEW

**Review by PCXDME — CHANGES_REQUESTED** [review]
1. package-lock.json should not exist in root folder
2. There should be a text box (Should we create another issue for this?)
3. Should we use Angular 1?

**Comment by PCXDME** [comment]
#14

**Comment by fhnaseer** [comment]
1. You mean add to gitignore?,
2. When working on other issues we can update it,
3. Why? It is just for testing purpose,

**Comment by PCXDME** [comment]
1. I mean the whole app is in "plot-editor" folder. There is package-lock.json in both root directory and in "plot-editor" directory. I think it looks like you did have package.json in root directory before and did run "npm install", so the package-lock.json was created in root directory. Then you move package.json to "plot-editor" folder?
2. Oh, OK
3. AngularJS (Angular 1) will be deprecated some time in the future. And I think that plain Javascript is enough. We did not actually use many of the core features of Angular anyways(such as template binding, state management, dependency injection). Also it might be easier to merge into project A with plain Javascript. It's still OK, I am just OCD about everything.

**Comment by fhnaseer** [comment]
That file was added by mistake, removed it,

**Review by PCXDME — APPROVED** [review]

**Pull request merged**
