### PR TITLE
Histogram, Bar Chart, Line Char, Scatter Plot Integration

### PR DESCRIPTION
**Pull request by PCXDME**
#32

### CODE REVIEW

**Review by fhnaseer — COMMENTED** [review]
Did you run 'npm run lint' on the code?,
Also format the documents. There is inconsistent spacing in some files,

**Comment by PCXDME** [comment]
Linting is OK now.
Can I add "mocha-eslint" @fhnaseer ?

**Review by fhnaseer — APPROVED** [review]

**Comment by syxolk** [comment]
Hi! We could also add `npm run lint` in your `.travis.yml` so that travis takes care of it.

**Comment by PCXDME** [comment]
@syxolk I have already used mocha-eslint, so there is no need for `npm run lint` anymore.
Thanks for suggestion.

**Comment by syxolk** [comment]
Yes, you executed it locally but we could also configure Travis to do it automatically for everyone on every push.

**Comment by PCXDME** [comment]
Yes, it does execute automatically now. You can try `npm run test`.
This is done by this file `test/lintTest.js`. 

eslint

**Comment by syxolk** [comment]
Sorry, I didn't see that.

**Pull request merged**
